language: go
go:
- 1.4
install:
- go get github.com/spf13/hugo
script: hugo
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: rafael.arque.ro
  region: eu-central-1
  local-dir: public
  skip_cleanup: true
  on:
    repo: arkeros/rafael.arque.ro
