# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rafael Arquero
tagline:          'A Jekyll theme'
description:	  '21 years. Redhead. Studying Mathematics and Computer Science at the <a href="http://www.ub.edu" target="_blank">UB</a>. Creator of <a href="http://omegan.net" target="_blank">Omegan</a>. Currently working at <a href="http://www.virtual-ad.com" target="_blank">Virtual AD</a>.'
url:              https://rafael.arque.ro
baseurl:          /

author:
  name:           'Rafael Arquero Gimeno'
  url:            https://rafael.arque.ro

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/arkeros/rafael.arque.ro
